mail:
  smtp:
    hostname: 127.0.0.1
    port: 3025
    username: test@example.test
    password: password
forms:
  - name: contact
    to: contact@example.com
    subject: Ich suche Kontakt!
    fields: [message]
    redirects:
      success: /forms/contact/success
redirects:
  error: /forms/error