id = "demo-site"
hostname = [ "localhost", "127.0.0.1" ]
baseurl = "http://localhost:2020"
locale = "en_US"
theme = "demo"
context_path = "/"

[ui]
force2fa = false
managerEnabled = true

[ui.2fa]
mail_from = "noreply@localhost.de"
mail_sender = "CondationCMS"
mail_title = "CondationCMS: your login code"
mail_message = '''
Hello <username>,

your login code: <code>
'''

[backup]
enabled = true
cron = "0 0 2 * * ?"
target = "/Users/thorstenmarx/entwicklung/backups"

[cache]
content = true

[modules]
active = ["example-module"]

[translation]
enabled = true
languages = ["de", "en"]

[[translation.mapping]]
language = "de"
site = "demo-de-site"

[[translation.mapping]]
site = "demo-site"
language = "en"