env = "dev"

[server]
port = 2020
ip = "127.0.0.1"

[ui]
secret = "super-secret-token"

[ipc]
port = 6868
password = "test_pwd"

[apm]
enabled = false
max_requests = 100
thread_limit = 10

[performance]
pool_enabled = false
pool_size = 10
pool_expire = 1000

[list]
test = ["eins", "zwei"]

[map]
test = {"key1"="value2", "key2"="value2"}
