id = "feature-site"
hostname = [ "localhost2" ]
baseurl = "http://localhost2:1010"
language = "en"
test = "Hallo"
theme = "test"

[cache]
content = true

[query.index]
mode = "PERSISTENT"

[modules]
active = [ "forms-module" ]

[api]
enabled = true